routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


/**
 *
 * Login view Route(s)
 */
Route::get('/', function () {
    return view('login');
});

Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser')->name('verify.user');

Auth::routes(['verify' => true]);

/**
 * Login Route(s)
 */
Route::get('login', 'AuthController@login')->name('login');
Route::post('login', 'AuthController@loginProcess');
Route::get('logout', 'AuthController@logout')->name('logout');

/**
 * OTP Route(s)
 */
#Route::post('verifyOTP/{otp}', 'AuthController@verifyOTP');
Route::post('verifyOTP', 'AuthController@verifyOTP')->name('verify-otp');

/**
 * Password Reset Link Route(s)
 */
Route::get('email', 'ForgotPassController@showRequestForm')->name('email');
Route::post('email', 'ForgotPassController@sendResetLinkEmail');

/**
 * Password Reset Route(s)
 */
Route::get('reset/{token}', 'ForgotPassController@verifyPassRequest')->name('verify.passrequest');
Route::post('reset', 'ForgotPassController@resetPass')->name('reset');

/**
 * Password Expiration Route(s)
 */
Route::get('expired-password','PwdExpirationController@showPasswordExpirationForm')->name('passwordExpiration');
Route::post('expired-password','PwdExpirationController@postPasswordExpiration');

/**
 * Change Password Route(s)
 */
Route::get('change-password', 'AuthController@passChangeForm')->name('change-password');
Route::post('update-password', 'AuthController@updatePassword');

/**
 * Dashboard Route
 */
Route::get('/home', 'HomeController@index')->name('home');

Route::group( ['middleware' => ['auth', 'has_permission', 'verified']], function() {
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions','PermissionController');

    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::put('profile/upload', ['as' => 'profile.upload', 'uses' => 'ProfileController@upload']);

    Route::resource('institution', 'InstitutionController');
    Route::resource('client', 'ClientController');
    
    
});

Route::get('/verification/phonenumber', 'Auth\RegisterController@generateRandomSecurityKey');

/**
 * Client Configurations Route(s)
 */
Route::group(['middleware' => ['auth', 'has_permission', 'verified'],['prefix' => 'Fees Configuration']], function () {
    Route::resource('fees_configuration', 'FeesController');
});

/**
 * Error Logs
 */
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Institution.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Institution extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/InstitutionController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use Carbon\Carbon;
use App\Institution;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class InstitutionController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth', 'verified']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $institutions = Institution::all();
        return view('institution.index', compact('institutions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('institution.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [

            'name' => 'required|unique:institutions',
            'company_reg_no' => 'required|max:15|unique:institutions',
            'kra_pin' => 'required|max:11|unique:institutions',
            'description' => 'required|max:255',
            'email' => 'required|email|unique:institutions',
            'phone_number' => 'required|max:10|unique:institutions',
            'postal_address' => 'required|max:11',
            'physical_address' => 'required|max:11|unique:institutions',

        ]);

        if ($validator->passes()) {
            // save institution
            $institution = new Institution();
            $institution->name = $request->input('name');
            $institution->company_reg_no = $request->input('company_reg_no');
            $institution->kra_pin = $request->input('kra_pin');
            $institution->description = $request->input('description');
            $institution->email = $request->input('email');
            $institution->phone_number = $request->input('phone_number');
            $institution->postal_address = $request->input('postal_address');
            $institution->physical_address = $request->input('physical_address');
            $institution->status = 0;
            $institution->active = 1;
            $institution->maker = Auth::user()->id;
            $institution->checker = '';
            $institution->created_at = Carbon::now();
            $institution->updated_at = Carbon::now();
            $institution->save();
    
            flash('Institution added successfully')->success();
            return redirect()->route('institution.index');
            
        } else {
            # validation failed
            $messages = $validator->errors();
            foreach ($messages->all() as $message) {
                flash('validation error! ' . '' . $message)->error();
            }
            return redirect()->back()->withInput(Input::all());
        }
       
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Institution  $institution
     * @return \Illuminate\Http\Response
     */
    public function show(Institution $institution)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Institution  $institution
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $institution = Institution::find($id);
        return view('institution.edit', compact('institution', $institution));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $institution = Institution::findOrFail($id);

        $institution->name = $request->input('name');
        $institution->company_reg_no = $request->input('company_reg_no');
        $institution->kra_pin = $request->input('kra_pin');
        $institution->description = $request->input('description');
        $institution->email = $request->input('email');
        $institution->phone_number = $request->input('phone_number');
        $institution->postal_address = $request->input('postal_address');
        $institution->physical_address = $request->input('physical_address');
        $institution->updated_at = Carbon::now();
        $institution->save();

        flash('Institution successfully updated.')->success();
        return redirect()->route('institution.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Institution  $institution
     * @return \Illuminate\Http\Response
     */
    public function destroy(Institution $institution)
    {
        //
    }
}

resources/views/Institution/create.blade.php
@extends('layouts.app')

@section('title', 'Institution')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Financial Institutions</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ url('home') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Institution Configuration</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        @include('flash::message')
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5><i class="fa fa-plus-square-o"></i> Add Institutions</h5>
                        <div class="ibox-tools">
                            <a href="{{ route('institution.index') }}" data-toggle="modal" rel="tooltip"
                               data-placement="top" title="Back to Institution">
                                <i class="fa fa-bank"></i>
                                <strong>Institution</strong>
                            </a>
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        {!! Form::open(array('url' => 'institution')) !!}

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group @if ($errors->has('companyName')) has-error @endif">
                                    {!! Form::label('companyName', 'Company Name') !!}
                                    {!! Form::text('name', '', array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group @if ($errors->has('registrationNumber')) has-error @endif">
                                    {!! Form::label('registrationNumber', 'Registration Number') !!}
                                    {!! Form::text('company_reg_no', '', array('class' => 'form-control')) !!}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group @if ($errors->has('email')) has-error @endif">
                                    {!! Form::label('email', 'Email Address') !!}
                                    {!! Form::text('email', '', array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group @if ($errors->has('phoneNumber')) has-error @endif">
                                    {!! Form::label('phoneNumber', 'Phone Number') !!}
                                    {!! Form::text('phone_number', '', array('class' => 'form-control')) !!}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group @if ($errors->has('krapin')) has-error @endif">
                                    {!! Form::label('krapin', 'KRA PIN') !!}
                                    {!! Form::text('kra_pin', '', array('class' => 'form-control')) !!}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group @if ($errors->has('physicalAddress')) has-error @endif">
                                    {!! Form::label('physicalAddress', 'Physical Address') !!}
                                    {!! Form::text('physical_address', '', array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group @if ($errors->has('postalAddress')) has-error @endif">
                                    {!! Form::label('postalAddress', 'Postal Address') !!}
                                    {!! Form::text('postal_address', '', array('class' => 'form-control')) !!}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group @if ($errors->has('postalAddress')) has-error @endif">
                                    {!! Form::label('description', 'Description') !!}
                                    {!! Form::textarea('description', '', array('class' => 'form-control')) !!}
                                </div>
                            </div>
                        </div>
                        {{ Form::submit('Submit', array('class' => 'btn btn-primary')) }}

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection

resources/views/Institution/edit.blade.php
@extends('layouts.app')

@section('title', 'Institution')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Financial Institutions</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ url('home') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Institution Configuration</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        @include('flash::message')
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5><i class="fa fa-plus-square-o"></i> Edit Institution</h5>
                        <div class="ibox-tools">
                            <a href="{{ route('institution.index') }}" data-toggle="modal" rel="tooltip"
                               data-placement="top" title="Back to Institution">
                                <i class="fa fa-bank"></i>
                                <strong>Institution</strong>
                            </a>
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        {!! Form::model($institution, array('route' => array('institution.update', $institution->id), 'method' => 'PUT')) !!}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group @if ($errors->has('companyName')) has-error @endif">
                                    {!! Form::label('companyName', 'Company Name') !!}
                                    {!! Form::text('name', null, array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group @if ($errors->has('registrationNumber')) has-error @endif">
                                    {!! Form::label('registrationNumber', 'Registration Number') !!}
                                    {!! Form::text('company_reg_no', null, array('class' => 'form-control')) !!}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group @if ($errors->has('email')) has-error @endif">
                                    {!! Form::label('email', 'Email Address') !!}
                                    {!! Form::text('email', null, array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group @if ($errors->has('phoneNumber')) has-error @endif">
                                    {!! Form::label('phoneNumber', 'Phone Number') !!}
                                    {!! Form::text('phone_number', null, array('class' => 'form-control')) !!}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group @if ($errors->has('krapin')) has-error @endif">
                                    {!! Form::label('krapin', 'KRA PIN') !!}
                                    {!! Form::text('kra_pin', null, array('class' => 'form-control')) !!}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group @if ($errors->has('physicalAddress')) has-error @endif">
                                    {!! Form::label('physicalAddress', 'Physical Address') !!}
                                    {!! Form::text('physical_address', null, array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group @if ($errors->has('postalAddress')) has-error @endif">
                                    {!! Form::label('postalAddress', 'Postal Address') !!}
                                    {!! Form::text('postal_address', null, array('class' => 'form-control')) !!}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group @if ($errors->has('postalAddress')) has-error @endif">
                                    {!! Form::label('description', 'Description') !!}
                                    {!! Form::textarea('description', null, array('class' => 'form-control')) !!}
                                </div>
                            </div>
                        </div>
                        {{ Form::submit('Update', array('class' => 'btn btn-primary')) }}

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection

resources/views/Institution/index.blade.php
@extends('layouts.app')

@section('title', 'Institution')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Financial Institutions</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ url('home') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Institution Configuration</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        @include('flash::message')

        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5><i class="fa fa-bank"></i> Registered Institutions</h5>
                        <div class="ibox-tools">
                            <a href="{{ route('institution.create') }}" data-toggle="modal" rel="tooltip"
                               data-placement="top" title="Add Institution">
                                <i class="fa fa-plus-square"></i>
                                Add Institution
                            </a>
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="userDatatable">
                                <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Physical Address</th>
                                    <th>Creation Date</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($institutions as $institution)
                                    <tr>
                                        <td>{{ $institution->id }}</td>
                                        <td>{{ $institution->name }}</td>
                                        <td>{{ $institution->email }}</td>
                                        <td>{{ $institution->physical_address }}</td>
                                        <td>{{ $institution->created_at->format('F d, Y h:ia') }}</td>
                                        <td class="text-right">
                                            @if($institution->id!=auth()->user()->id)
                                                <a href="{{ URL::to('institution/'.$institution->id.'/edit') }}" title="Edit Institution"
                                                   class="btn btn-success btn-sm" rel="tootltip" data-placement="top">
                                                    <i class="fa fa-edit"></i>
                                                </a>

                                                <form action="{{ route('institution.destroy', $institution) }}" method="post"
                                                      style="display:inline-block;" class="delete-form">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="button" rel="tooltip"
                                                            class="btn btn-danger btn-sm" title="Delete Institution" data-placement="top"
                                                            onclick="confirm('{{ __('Are you sure you want to delete this institution?') }}') ? this.parentElement.submit() : ''">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Physical Address</th>
                                    <th>Creation Date</th>
                                    <th>Actions</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{--<div class="modal fade" id="addUserModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">--}}
    {{--<div class="modal-dialog">--}}
    {{--<div class="modal-content">--}}
    {{--<div class="modal-header">--}}
    {{--<h4 class="modal-title" id="myModalLabel"><i class="fa fa-user-plus"></i> Add Institution </institution {{--</div>--}}
    {{--<div class="modal-body">--}}
    {{--<h3>Registration form here</h3>--}}
    {{--</div>--}}
    {{--<div class="modal-footer">--}}
    {{--<button type="button" class="btn btn-default btn-rounded" data-dismiss="modal">Close</button>--}}
    {{--<button type="button" class="btn btn-primary btn-rounded">Save changes</button>--}}
    {{--</div>--}}
    {{--</div>--}}
    {{--</div>--}}
    {{--</div>--}}
@endsection