routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


/**
 *
 * Login view Route(s)
 */
Route::get('/', function () {
    return view('login');
});

Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser')->name('verify.user');

Auth::routes(['verify' => true]);

/**
 * Login Route(s)
 */
Route::get('login', 'AuthController@login')->name('login');
Route::post('login', 'AuthController@loginProcess');
Route::get('logout', 'AuthController@logout')->name('logout');

/**
 * OTP Route(s)
 */
#Route::post('verifyOTP/{otp}', 'AuthController@verifyOTP');
Route::post('verifyOTP', 'AuthController@verifyOTP')->name('verify-otp');

/**
 * Password Reset Link Route(s)
 */
Route::get('email', 'ForgotPassController@showRequestForm')->name('email');
Route::post('email', 'ForgotPassController@sendResetLinkEmail');

/**
 * Password Reset Route(s)
 */
Route::get('reset/{token}', 'ForgotPassController@verifyPassRequest')->name('verify.passrequest');
Route::post('reset', 'ForgotPassController@resetPass')->name('reset');

/**
 * Password Expiration Route(s)
 */
Route::get('expired-password','PwdExpirationController@showPasswordExpirationForm')->name('passwordExpiration');
Route::post('expired-password','PwdExpirationController@postPasswordExpiration');

/**
 * Change Password Route(s)
 */
Route::get('change-password', 'AuthController@passChangeForm')->name('change-password');
Route::post('update-password', 'AuthController@updatePassword');

/**
 * Dashboard Route
 */
Route::get('/home', 'HomeController@index')->name('home');

Route::group( ['middleware' => ['auth', 'has_permission', 'verified']], function() {
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions','PermissionController');

    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::put('profile/upload', ['as' => 'profile.upload', 'uses' => 'ProfileController@upload']);

    Route::resource('institution', 'InstitutionController');
    Route::resource('client', 'ClientController');
    
    
});

Route::get('/verification/phonenumber', 'Auth\RegisterController@generateRandomSecurityKey');

/**
 * Client Configurations Route(s)
 */
Route::group(['middleware' => ['auth', 'has_permission', 'verified'],['prefix' => 'Fees Configuration']], function () {
    Route::resource('fees_configuration', 'FeesController');
});

/**
 * Error Logs
 */
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

resources/views/fees_configuration/edit.blade.php
@extends('layouts.app')

@section('title', 'Fee Configurations')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Users</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ url('home') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Edit Fees Group</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        @include('flash::message')
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5><i class="fa fa-plus-square-o"></i> Edit Fee Group</h5>
                        <div class="ibox-tools">
                            <a href="{{ route('fees_configuration.index') }}" data-toggle="modal" rel="tooltip"
                               data-placement="top" title="Back to List">
                                <i class="fa fa-money"></i>
                                <strong>Fee Groups</strong>
                            </a>
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        {!! Form::model($fee, array('route' => array('fees_configuration.update', $fee->id), 'method' => 'PUT')) !!}

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group @if ($errors->has('groupName')) has-error @endif">
                                    {!! Form::label('groupName', 'Group Name') !!}
                                    {!! Form::text('group_name', null, array('class' => 'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group @if ($errors->has('feeCharge')) has-error @endif">
                                    {!! Form::label('feeCharge', 'Fees') !!}
                                    {!! Form::text('fee', null, array('class' => 'form-control')) !!}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group @if ($errors->has('percentage')) has-error @endif">
                                    {!! Form::label('percentage', 'Percentage') !!}
                                    {!! Form::number('percent'), null, array('class' => 'form-control') !!}
                                </div>
                            </div>
                        </div>
                        {{ Form::submit('Update', array('class' => 'btn btn-primary')) }}

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/fees_configuration/index.blade.php
@extends('layouts.app')

@section('title', 'Fee Configurations')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Users</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ url('home') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item">
                    <a>Configurations</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Fees Configuration</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        @include('flash::message')

        <div class="row">
            <div class="col-md-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5>Fee Groups</h5>
                        <div class="ibox-tools">
                            <a href="#" data-toggle="modal" data-target="#addFeeModal" rel="tooltip" data-placement="top" title="Add Fee">
                                <i class="fa fa-money"></i>
                                Add Fee Group
                            </a>
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="userDataTable">
                                <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Group Name</th>
                                    <th>Fee(s)</th>
                                    <th>% Charge</th>
                                    <th>Creation Date</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($fees as $fee)
                                    <tr>
                                        <td>{{ $fee->id }}</td>
                                        <td>{{ $fee->group_name }}</td>
                                        <td>{{ $fee->fee }}</td>
                                        <td>{{ $fee->percent }}</td>
                                        <td>{{ $fee->created_at->format('F d, Y h:ia') }}</td>
                                        <td class="text-right">
                                            @if($fee->id!=auth()->user()->id)
                                                <a href="{{ URL::to('fees_configuration/'.$fee->id.'/edit') }}" title="Edit Institution"
                                                   class="btn btn-success btn-sm" rel="tootltip" data-placement="top">
                                                    <i class="fa fa-edit"></i>
                                                </a>

                                                <form action="{{ route('fees_configuration.destroy', $fee) }}" method="post"
                                                      style="display:inline-block;" class="delete-form">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="button" rel="tooltip"
                                                            class="btn btn-danger btn-sm" title="Delete Group" data-placement="top"
                                                            onclick="confirm('{{ __('Are you sure you want to delete this group?') }}') ? this.parentElement.submit() : ''">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>No</th>
                                    <th>Group Name</th>
                                    <th>Fee(s)</th>
                                    <th>% Charge</th>
                                    <th>Creation Date</th>
                                    <th>Actions</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div id="addFeeModal" class="modal fade animated fadeInDown" role="dialog">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"><i class="fa fa-money"></i> New Fee Group</h4>
                </div>
                <div class="modal-body">
                    <form action="{{ 'fees_configuration.store' }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="feeGroup">Group Name</label>
                                    <input type="text" class="form-control" name="group_name" id="feeGroup"
                                           value="{{ old('group_name') }}" autocomplete="off" required>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="fee">Fee</label>
                                    <input type="number" class="form-control" name="fee" id="fee"
                                           value="{{ old('fee') }}" autocomplete="off" required>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="rate">Percentage</label>
                                    <input type="text" class="form-control" name="percent" id="percentage"
                                           autocomplete="off" value="{{ old('percentage') }}" required>
                                </div>
                            </div>
                        </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
                </form>
            </div>

        </div>
    </div>
@endsection