routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


/**
 *
 * Login view Route(s)
 */
Route::get('/', function () {
    return view('login');
});

Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser')->name('verify.user');

Auth::routes(['verify' => true]);

/**
 * Login Route(s)
 */
Route::get('login', 'AuthController@login')->name('login');
Route::post('login', 'AuthController@loginProcess');
Route::get('logout', 'AuthController@logout')->name('logout');

/**
 * OTP Route(s)
 */
#Route::post('verifyOTP/{otp}', 'AuthController@verifyOTP');
Route::post('verifyOTP', 'AuthController@verifyOTP')->name('verify-otp');

/**
 * Password Reset Link Route(s)
 */
Route::get('email', 'ForgotPassController@showRequestForm')->name('email');
Route::post('email', 'ForgotPassController@sendResetLinkEmail');

/**
 * Password Reset Route(s)
 */
Route::get('reset/{token}', 'ForgotPassController@verifyPassRequest')->name('verify.passrequest');
Route::post('reset', 'ForgotPassController@resetPass')->name('reset');

/**
 * Password Expiration Route(s)
 */
Route::get('expired-password','PwdExpirationController@showPasswordExpirationForm')->name('passwordExpiration');
Route::post('expired-password','PwdExpirationController@postPasswordExpiration');

/**
 * Change Password Route(s)
 */
Route::get('change-password', 'AuthController@passChangeForm')->name('change-password');
Route::post('update-password', 'AuthController@updatePassword');

/**
 * Dashboard Route
 */
Route::get('/home', 'HomeController@index')->name('home');

Route::group( ['middleware' => ['auth', 'has_permission', 'verified']], function() {
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions','PermissionController');

    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::put('profile/upload', ['as' => 'profile.upload', 'uses' => 'ProfileController@upload']);

    Route::resource('institution', 'InstitutionController');
    Route::resource('client', 'ClientController');
    
    
});

Route::get('/verification/phonenumber', 'Auth\RegisterController@generateRandomSecurityKey');

/**
 * Client Configurations Route(s)
 */
Route::group(['middleware' => ['auth', 'has_permission', 'verified'],['prefix' => 'Fees Configuration']], function () {
    Route::resource('fees_configuration', 'FeesController');
});

/**
 * Error Logs
 */
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Permission extends \Spatie\Permission\Models\Permission
{
    public static function defaultPermissions()
    {
        $array = array(
            'viewUser' => 'is able to view users',
            'addUser' => 'is able to add users',
            'editUser' => 'is able to edit users',
            'deleteUser' => 'is able to delete users',

            'viewRole' => 'is able to view roles',
            'addRole' => 'is able to add roles',
            'editRole' => 'is able to edit roles',
            'deleteRole' => 'is able to delete roles',

            'viewPermission' => 'is able to view permissions',
            'addPermission' => 'is able to add permissions',
            'editPermission' => 'is able to edit permissions',
            'deletePermission' => 'is able to delete permissions',

            'viewConfiguration' => 'is able to view configuration menu',
            'viewUserManagement' => 'is able to view user management menu',
            'viewClientUsers' => 'is able to view client users menu',
            'viewFinancialInstitution' => 'is able to view financial institution menu'

        );

        return $array;
    }
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use App\Permission;
use Illuminate\Http\Request;

class PermissionController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $permissions = Permission::all();
        return view('permissions.index', compact('permissions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::get(); //Get all roles
        return view('permissions.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:40',
        ]);
        $permission = new Permission();
        $permission->name = $request->name;
        $permission->save();
        if ($request->roles <> '') {
            foreach ($request->roles as $key => $value) {
                $role = Role::find($value);
                $role->permissions()->attach($permission);
            }
        }

        flash('Success, Permission added successfully')->success();
        return redirect()->route('permissions.index');
    }

    public function edit(Permission $permission)
    {
        return view('permissions.edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Permission $permission
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Permission $permission)
    {
        $this->validate($request, [
            'name' => 'required',
        ]);

        $permission->name = $request->name;
//        $permission->description = $request->description;
        $permission->save();

        flash('Success, Permission ' .$permission->name. 'updated!');
        return redirect()->route('permissions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Permission $permission
     * @return \Illuminate\Http\Response
     */
    public function destroy(Permission $permission)
    {
        $permission->delete();

        flash('Success, Permission deleted successfully!');
        return redirect()->route('permissions.index');
    }
}

resources/views/permissions/create.blade.php
@extends('layouts.app')

@section('title', ' Create Permission')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Permissions</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ url('home') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item">
                    <a>Permission Management</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Add Permission</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5><i class='fa fa-plus-square-o'></i> Add Permission</h5>
                        <div class="ibox-tools">
                            <a href="{{ route('permissions.index') }}" rel="tooltip" data-placement="top" title="Back to Permissions">
                                <i class="fa fa-key"></i>
                                <strong>Permissions</strong>
                            </a>
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        {{ Form::open(array('url' => 'permissions')) }}

                        <div class="form-group">
                            {{ Form::label('name', 'Name') }}
                            {{ Form::text('name', '', array('class' => 'form-control')) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('name', 'Description') }}
                            {{ Form::text('name', '', array('class' => 'form-control')) }}
                        </div>
                        <br>
                        @if(!$roles->isEmpty())
                            <h4>Assign Permission to Roles</h4>

                            @foreach ($roles as $role)
                                {{ Form::checkbox('roles[]',  $role->id ) }}
                                {{ Form::label($role->name, ucfirst($role->name)) }}<br>

                            @endforeach
                        @endif
                        <br>
                        {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}

                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/permissions/edit.blade.php
@extends('layouts.app')

@section('title', ' Edit Permission')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Permissions</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ url('home') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item">
                    <a>Permission Management</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Edit Permission</strong>
                </li>
            </ol>
        </div>
    </div>

        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox">
                        <div class="ibox-title">
                        <h5><i class='fa fa-key'></i> Edit - {{$permission->name}}</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        {{ Form::model($permission, array('route' => array('permissions.update', $permission->id), 'method' => 'PUT')) }}{{-- Form model binding to automatically populate our fields with permission data --}}

                        <div class="form-group">
                            {{ Form::label('name', 'Permission Name') }}
                            {{ Form::text('name', null, array('class' => 'form-control')) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('description', 'Description') }}
                            {{ Form::text('description', null, array('class' => 'form-control')) }}
                        </div>
                        <br>
                        {{ Form::submit('Edit', array('class' => 'btn btn-primary')) }}

                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/permissions/index.blade.php
@extends('layouts.app')

@section('title', 'Permissions')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Permissions</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ url('home') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item">
                    <a>Permission Management</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Permission Registry</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>System Permissions</h5>
                        <div class="ibox-tools">
                            <a href="{{ route('permissions.create') }}"  data-target="#addPermModal" rel="tooltip"
                               data-placement="top" title="Add Permission">
                                <i class="fa fa-key"></i>
                                Add Permission
                            </a>
                            <a href="{{ route('roles.index') }}" rel="tooltip"
                               data-placement="top" title="View Roles">
                                <i class="fa fa-user-circle-o"></i>
                                Roles
                            </a>
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="userDatatable">
                                <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Permission</th>
                                    <th>Description</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($permissions as $permission)
                                    <tr>
                                        <td>{{ $permission->id }}</td>
                                        <td>{{ $permission->name }}</td>
                                        <td>{{ $permission->description }}</td>
                                        <td class="text-right">
                                            @if($permission->id!=auth()->user()->id)
                                            <a href="{{ URL::to('permissions/'.$permission->id.'/edit') }}" title="Edit Permission"
                                               class="btn btn-success btn-sm" rel="tootltip" data-placement="top">
                                                <i class="fa fa-edit"></i>
                                            </a>

                                            <form action="{{ route('permissions.destroy', $permission) }}" method="post"
                                                  style="display:inline-block;" class="delete-form">
                                                @csrf
                                                @method('delete')
                                                <button type="button" rel="tooltip"
                                                        class="btn btn-danger btn-sm" title="Delete Permission" data-placement="top"
                                                        onclick="confirm('{{ __('Are you sure you want to delete this permission?') }}') ? this.parentElement.submit() : ''">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>No</th>
                                    <th>Permission</th>
                                    <th>Description</th>
                                    <th>Actions</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection