routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


/**
 *
 * Login view Route(s)
 */
Route::get('/', function () {
    return view('login');
});

Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser')->name('verify.user');

Auth::routes(['verify' => true]);

/**
 * Login Route(s)
 */
Route::get('login', 'AuthController@login')->name('login');
Route::post('login', 'AuthController@loginProcess');
Route::get('logout', 'AuthController@logout')->name('logout');

/**
 * OTP Route(s)
 */
#Route::post('verifyOTP/{otp}', 'AuthController@verifyOTP');
Route::post('verifyOTP', 'AuthController@verifyOTP')->name('verify-otp');

/**
 * Password Reset Link Route(s)
 */
Route::get('email', 'ForgotPassController@showRequestForm')->name('email');
Route::post('email', 'ForgotPassController@sendResetLinkEmail');

/**
 * Password Reset Route(s)
 */
Route::get('reset/{token}', 'ForgotPassController@verifyPassRequest')->name('verify.passrequest');
Route::post('reset', 'ForgotPassController@resetPass')->name('reset');

/**
 * Password Expiration Route(s)
 */
Route::get('expired-password','PwdExpirationController@showPasswordExpirationForm')->name('passwordExpiration');
Route::post('expired-password','PwdExpirationController@postPasswordExpiration');

/**
 * Change Password Route(s)
 */
Route::get('change-password', 'AuthController@passChangeForm')->name('change-password');
Route::post('update-password', 'AuthController@updatePassword');

/**
 * Dashboard Route
 */
Route::get('/home', 'HomeController@index')->name('home');

Route::group( ['middleware' => ['auth', 'has_permission', 'verified']], function() {
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions','PermissionController');

    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
    Route::put('profile/upload', ['as' => 'profile.upload', 'uses' => 'ProfileController@upload']);

    Route::resource('institution', 'InstitutionController');
    Route::resource('client', 'ClientController');
    
    
});

Route::get('/verification/phonenumber', 'Auth\RegisterController@generateRandomSecurityKey');

/**
 * Client Configurations Route(s)
 */
Route::group(['middleware' => ['auth', 'has_permission', 'verified'],['prefix' => 'Fees Configuration']], function () {
    Route::resource('fees_configuration', 'FeesController');
});

/**
 * Error Logs
 */
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends \Spatie\Permission\Models\Role
{
    //
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use App\Permission;
use Illuminate\Http\Request;

class RoleController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $roles = Role::all();
        return view('roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all();//Get all permissions
        return view('roles.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
                'name' => 'required|unique:roles|max:10',
                'permissions' => 'required',
            ]
        );
        $role = new Role();
        $role->name = $request->name;
        $role->save();
        if ($request->permissions <> '') {
            $role->permissions()->attach($request->permissions);
        }
        return redirect()->route('roles.index')->with('success', 'Roles added successfully');
    }

    public function edit($id)
    {
        $role = Role::findOrFail($id);
        $permissions = Permission::all();
        return view('roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Role $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::findOrFail($id);//Get role with the given id
        //Validate name and permission fields
        $this->validate($request, [
            'name' => 'required|max:10|unique:roles,name,' . $id,
            'permissions' => 'required',
        ]);
        $input = $request->except(['permissions']);
        $role->fill($input)->save();
        if ($request->permissions <> '') {
            $role->permissions()->sync($request->permissions);
        }
        return redirect()->route('roles.index')->with('success', 'Roles updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Role $role
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();
        return redirect()->route('roles.index')
            ->with('success',
                'Role deleted successfully!');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')

@section('title', ' Add Role')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Roles</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ url('home') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item">
                    <a>Role Management</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Role Registry</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5><i class='fa fa-plus-square-o'></i> Add Role</h5>
                        <div class="ibox-tools">
                            <a href="{{ route('roles.index') }}" rel="tooltip" data-placement="top"
                               title="Back to Roles">
                                <i class="fa fa-user-secret"></i>
                                <strong>Roles</strong>
                            </a>
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        {{ Form::open(array('url' => 'roles')) }}

                        <div class="form-group">
                            {{ Form::label('name', 'Name') }}
                            {{ Form::text('name', null, array('class' => 'form-control')) }}
                        </div>

                        <div class="form-group">
                            {{ Form::label('name', 'Description') }}
                            {{ Form::text('description', '', array('class' => 'form-control')) }}
                        </div>

                        <h5><b>Assign Permissions</b></h5>

                        <div class='form-group'>
                            @foreach ($permissions as $permission)
                                {{ Form::checkbox('permissions[]',  $permission->id ) }}
                                {{ Form::label($permission->name, ucfirst($permission->name)) }}<br>

                            @endforeach
                        </div>

                        {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}

                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')

@section('title', ' Edit Role')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Roles</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ url('home') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item">
                    <a>Role Management</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Edit Role</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5><i class="fa fa-user-secret"></i> Edit Role - {{ $role->name }}</h5>
                        <div class="ibox-tools">
                            <a href="{{ route('roles.index') }}" rel="tooltip"
                               data-placement="top" title="Back to Roles">
                                <i class="fa fa-user-secret"></i>
                                Roles
                            </a>
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        {{ Form::model($role, array('route' => array('roles.update', $role->id), 'method' => 'PUT')) }}

                        <div class="form-group">
                            {{ Form::label('name', 'Role Name') }}
                            {{ Form::text('name', null, array('class' => 'form-control')) }}
                        </div>

                        <div class="form-group">
                            {{ Form::label('description', 'Description') }}
                            {{ Form::text('description', null, array('class' => 'form-control')) }}
                        </div>

                        <h5><b>Assign Permissions</b></h5>
                        @foreach ($permissions as $permission)

                            {{Form::checkbox('permissions[]',  $permission->id, $role->permissions ) }}
                            {{Form::label($permission->name, ucfirst($permission->name)) }}<br>

                        @endforeach
                        <br>
                        {{ Form::submit('Edit', array('class' => 'btn btn-primary')) }}

                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')

@section('title', ' Roles')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Roles</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ url('home') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item">
                    <a>Role Management</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Role Registry</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        @include('flash::message')
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5><i class="fa fa-user-secret"></i> User Roles</h5>
                        <div class="ibox-tools">
                            <a href="{{ route('roles.create') }}"  data-target="#addPermModal" rel="tooltip"
                               data-placement="top" title="Add Role">
                                <i class="fa fa-user-secret"></i>
                                Add Role
                            </a>
                            <a href="{{ route('permissions.index') }}" rel="tooltip"
                               data-placement="top" title="View Permissions">
                                <i class="fa fa-key"></i>
                                Permissions
                            </a>
                            <a href="{{ route('users.index') }}" rel="tooltip"
                               data-placement="top" title="View Users">
                                <i class="fa fa-user-circle-o"></i>
                                Users
                            </a>
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th>Role</th>
                                    <th style="width: 85%;">Permissions</th>
                                    <th>Action</th>
                                </tr>
                                </thead>

                                <tbody>
                                @foreach ($roles as $role)
                                    <tr>

                                        <td>{{ $role->name }}</td>

                                        <td>{{ str_replace(array('[',']','"'),' ', $role->permissions()->pluck('name')) }}</td>
                                        <td class="text-right">
                                            <a href="{{ URL::to('roles/'.$role->id.'/edit') }}" title="Edit Role"
                                               class="btn btn-success btn-sm" rel="tootltip" data-placement="top">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            <form action="{{ route('roles.destroy', $role) }}" method="post"
                                                  style="display:inline-block;" class="delete-form">
                                                @csrf
                                                @method('delete')
                                                <button type="button" rel="tooltip"
                                                        class="btn btn-danger btn-sm" title="Delete Role" data-placement="top"
                                                        onclick="confirm('{{ __('Are you sure you want to delete this role?') }}') ? this.parentElement.submit() : ''">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection